import os
import asyncio
import datetime
import subprocess
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
import edge_tts
import uuid

app = FastAPI()

VOICE = "en-US-AriaNeural"

@app.websocket("/chat/stream")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    
    today = datetime.datetime.now().strftime("%Y_%m_%d")
    session_name = f"android_{today}"
    
    try:
        while True:
            # 1. Wait for Android to send the transcribed text
            data = await websocket.receive_text()
            print(f"🎙️ Received from Android: {data}")
            
            # 2. Tell Android we are thinking
            await websocket.send_json({"type": "status", "message": "Thinking..."})
            
            # 3. Call Hermes
            env = os.environ.copy()
            env["PATH"] = f"/home/service/.local/bin:{env.get('PATH', '')}"
            
            try:
                # We use subprocess.run for now, but to TRULY stream Hermes text token-by-token 
                # we would need to hook into its stdout asynchronously. For this first step, 
                # we'll get the full text from Hermes, but stream the AUDIO generation back to Android.
                result = await asyncio.to_thread(
                    subprocess.run,
                    ["hermes", "-z", data, "--continue", session_name],
                    capture_output=True,
                    text=True,
                    check=True,
                    env=env
                )
                reply_text = result.stdout.strip()
            except subprocess.CalledProcessError as e:
                reply_text = "I'm sorry, I encountered an error."
                print(f"Error: {e.stderr}")
            except FileNotFoundError:
                reply_text = "Hermes binary not found."
                
            print(f"💬 Hermes says: {reply_text}")
            
            # Send the text to the UI immediately
            await websocket.send_json({"type": "text", "message": reply_text})
            
            # 4. Stream the Audio bytes as they are generated by Edge-TTS
            await websocket.send_json({"type": "status", "message": "Speaking..."})
            
            communicate = edge_tts.Communicate(reply_text, VOICE)
            
            # We stream the mp3 chunks over the websocket directly! No file saving needed.
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    # Send raw binary audio chunk
                    await websocket.send_bytes(chunk["data"])
                    
            # Tell Android we finished sending this audio stream
            await websocket.send_json({"type": "audio_end"})
            
    except WebSocketDisconnect:
        print("Android disconnected.")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
