import os
import asyncio
import datetime
import subprocess
from typing import Set
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from pydantic import BaseModel
import edge_tts
import uuid

app = FastAPI()

VOICE = "en-US-AriaNeural"

# Connected phone clients — used to push unsolicited notifications
# (agent events from ANY running session on ANY host).
connected_clients: Set[WebSocket] = set()


class HermesEvent(BaseModel):
    hook_event_name: str = ""
    tool_name: str | None = None
    tool_input: dict | None = None
    session_id: str = ""
    cwd: str = ""
    extra: dict = {}


@app.post("/hermes-events")
async def hermes_event(event: HermesEvent):
    """Receive shell-hook events from any Hermes host and relay them to the phone."""
    kind = "response"
    title = "Hermes finished a session"
    message = ""

    if event.hook_event_name == "post_tool_call" and event.tool_name == "clarify":
        kind = "question"
        title = "Hermes is waiting for your input"
        question = (event.tool_input or {}).get("question") or "The agent asked you a question"
        choices = (event.tool_input or {}).get("choices") or []
        message = question
        if choices:
            message += "  Options: " + " | ".join(str(c) for c in choices)
    elif event.hook_event_name == "pre_approval_request":
        kind = "approval"
        title = "Hermes needs your approval"
        message = (event.extra or {}).get("description") or (event.extra or {}).get("command") or "The agent is waiting for approval"
    else:
        # on_session_end and anything else
        title = "Hermes finished"
        message = (event.extra or {}).get("session_key") or event.session_id or "A session just completed"

    payload = {
        "type": "notify",
        "kind": kind,
        "title": title,
        "message": message,
        "session_id": event.session_id,
        "event": event.hook_event_name,
        "host": (event.extra or {}).get("host", ""),
    }

    stale = []
    for ws in connected_clients:
        try:
            await ws.send_json(payload)
        except Exception:
            stale.append(ws)
    for ws in stale:
        connected_clients.discard(ws)

    print(f"📣 Relayed {kind} event to {len(connected_clients)} phone(s): {title}")
    return {"ok": True, "relayed": len(connected_clients)}


@app.websocket("/chat/stream")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    connected_clients.add(websocket)
    print(f"🔌 Phone connected ({len(connected_clients)} total)")

    today = datetime.datetime.now().strftime("%Y_%m_%d")
    session_name = f"android_{today}"

    try:
        while True:
            # 1. Wait for Android to send the transcribed text
            data = await websocket.receive_text()
            print(f"🎙️ Received from Android: {data}")

            # 2. Tell Android we are thinking
            await websocket.send_json({"type": "status", "message": "Thinking..."})

            # 3. Call Hermes
            env = os.environ.copy()
            env["PATH"] = f"/home/service/.local/bin:{env.get('PATH', '')}"

            try:
                result = await asyncio.to_thread(
                    subprocess.run,
                    ["hermes", "-z", data, "--continue", session_name],
                    capture_output=True,
                    text=True,
                    check=True,
                    env=env
                )
                reply_text = result.stdout.strip()
            except subprocess.CalledProcessError as e:
                reply_text = "I'm sorry, I encountered an error."
                print(f"Error: {e.stderr}")
            except FileNotFoundError:
                reply_text = "Hermes binary not found."

            print(f"💬 Hermes says: {reply_text}")

            # Send the text to the UI immediately
            await websocket.send_json({"type": "text", "message": reply_text})

            # 4. Stream the Audio bytes as they are generated by Edge-TTS
            await websocket.send_json({"type": "status", "message": "Speaking..."})

            communicate = edge_tts.Communicate(reply_text, VOICE)

            # We stream the mp3 chunks over the websocket directly! No file saving needed.
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    # Send raw binary audio chunk
                    await websocket.send_bytes(chunk["data"])

            # Tell Android we finished sending this audio stream
            await websocket.send_json({"type": "audio_end"})

    except WebSocketDisconnect:
        print("Android disconnected.")
    finally:
        connected_clients.discard(websocket)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
